### PR TITLE
Update x86.d

### PR DESCRIPTION
**Pull request by steviegt6**

### CODE REVIEW

**Comment by steviegt6** [comment]
LGTM, can we get this merged? ASAP!

**Comment by steviegt6** [comment]
cc: @cetio @ppebb @smug-b @chik3r @chairclr @hakusaro

**Comment by chairclr** [comment]
> cc: @cetio @ppebb @Smug-B @Chik3r @chairclr @hakusaro

Why was I cc'd?

**Comment by hakusaro** [comment]
> > cc: @cetio @ppebb @Smug-B @Chik3r @chairclr @hakusaro
> 
> Why was I cc'd?

Why was I cc'd?

**Pull request merged**
